project_id = "orlypvtllefclnwjayyf"

[functions.send-daily-notifications]
verify_jwt = false

[functions.send-test-notification]
verify_jwt = true

[functions.get-vapid-key]
verify_jwt = false

[functions.save-push-subscription]
verify_jwt = true

[functions.line-webhook]
verify_jwt = false

[functions.send-line-daily]
verify_jwt = false
